### ISSUE TITLE
Module is not installable with pip

### ISSUE THREAD

**Issue by krishvk** [Haider-Ali-Dev/create-pypi-project#1]
❯ python3 -m pip install --user create-pypi-project                                                                                                                    
Collecting create-pypi-project
  ERROR: Could not find a version that satisfies the requirement create-pypi-project (from versions: none)
ERROR: No matching distribution found for create-pypi-project

**Comment by haiderlikesrust** [comment]
```
pip install create-pypi-project
```

**Comment by krishvk** [comment]
Still same error

```
pip install create-pypi-project
ERROR: Could not find a version that satisfies the requirement create-pypi-project (from versions: none)
ERROR: No matching distribution found for create-pypi-project
```

**Comment by haiderlikesrust** [comment]
Maybe something wrong with your python version, also this project isn't maintained. Check https://python-poetry.org/
